[package]
name = "thunders"
version = "0.1.0"
edition = "2021"
authors = ["Drin"]
description = "Core no_std RF protocol stack for Nordic nRF radios"
license = "MIT OR Apache-2.0"

[dependencies]
heapless = { workspace = true }
embassy-time = { workspace = true }
defmt = { workspace = true, optional = true }

[features]
default = []
defmt = ["dep:defmt", "heapless/defmt"]
